# Generated by Django 5.0.1 on 2024-02-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_on',
        ),
    ]
