# Generated by Django 5.0.1 on 2024-02-06 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 15, 7, 47, 138431, tzinfo=datetime.timezone.utc)),
        ),
    ]
